---
 - name: ensure tomcat is installed
   apt:  pkg=tomcat{{tomcat_version}},tomcat{{tomcat_version}}-admin state=installed
   when: ansible_os_family == 'Debian'
   tags: [packages,tomcat]

 - name: ensure tomcat are configured
   template: src=server.xml.j2 dest={{tomcat_conf_dir}}/server.xml mode=0640 owner=tomcat{{tomcat_version}} group=tomcat{{tomcat_version}}
   notify: reload tomcat
   tags: [configuration,tomcat]

 - name: ensure users and role are configured
   template: src=tomcat-users.xml.j2 dest={{tomcat_conf_dir}}/tomcat-users.xml mode=0640 owner=tomcat{{tomcat_version}} group=tomcat{{tomcat_version}}
   notify: reload tomcat
   tags: [configuration,tomcat]

 - name: ensure tomcat is running
   service: name=tomcat{{tomcat_version}} state=running enabled=yes
   tags: [service,tomcat]
